# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Geoff Foley Dot Com"
email: geoff@geofffoley.com
description: >- # this means to ignore newlines until "baseurl:"
  The online home of Geoff Foley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geofffoley.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  geofffoley

permalink: /:title/

collections_dir: collections

collections:
  poetry:
    output: true
    title: Poetry
    permalink: /poetry/:title:output_ext

  posts:
    output: true
    title: The Foley Bag
    permalink: /blog/:title:output_ext

  fiction:
    output: true
    title: Stories
    permalink: /fiction/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - about.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
